#!/usr/bin/env python3
"""Generate (or verify) skills.json -- the jar's machine-readable index.

An agent fetching this repo reads ONE file to route, instead of crawling
directories: skills.json lists every jar skill with its name, category,
description (the frontmatter routing text), path
(`<category>/<skill>/SKILL.md`), and optional metadata for tags, core status,
maturity, and evidence.

GENERATED -- never edit by hand. The audit gate (scripts/audit-jar.py) runs
this with --check, so a stale index fails the build instead of rotting.

It also writes docs/core-skills.md from the same index so core/meta skills stay
discoverable without becoming a separate install category.

Usage:
    python scripts/gen-index.py            # (re)write generated index files
    python scripts/gen-index.py --check    # exit 0 if in sync, 1 if stale
"""

import argparse
import json
import sys

import jarlib

ROOT = jarlib.repo_root()
INDEX = ROOT / "skills.json"
CORE_DOC = ROOT / "docs" / "core-skills.md"


def build_index():
    skills = []
    for s in jarlib.discover_skills(ROOT):
        skills.append(jarlib.skill_index_entry(s, ROOT))
    skills.sort(key=lambda s: (s["category"], s["name"]))
    return {
        "_generated": "by scripts/gen-index.py -- do not edit by hand; "
                      "the audit gate fails if this file is stale",
        "skills": skills,
    }


def render(index):
    return json.dumps(index, indent=2, ensure_ascii=False) + "\n"


def rel_link_from_docs(path):
    return "../" + path


def render_core_doc(index):
    core = [s for s in index["skills"] if s.get("core")]
    lines = [
        "# Core Skills",
        "",
        "> GENERATED by `scripts/gen-index.py` -- do not edit by hand.",
        "",
        "Core skills are the jar's self-improvement substrate. They remain in",
        "their installable categories; `core: true` and `meta` tags only make",
        "them easier to discover.",
        "",
    ]
    if not core:
        lines += ["No core skills are currently declared.", ""]
    else:
        lines += [
            "| Skill | Category | Tags | Maturity | Evidence |",
            "|-------|----------|------|----------|----------|",
        ]
        for skill in core:
            tags = ", ".join(skill.get("tags", [])) or "-"
            maturity = skill.get("maturity", "-")
            evidence = skill.get("evidence")
            evidence_cell = "-"
            if evidence:
                evidence_cell = "[proof](%s)" % rel_link_from_docs(evidence)
            lines.append(
                "| [%s](%s) | %s | %s | %s | %s |" % (
                    skill["name"],
                    rel_link_from_docs(skill["path"]),
                    skill["category"],
                    tags,
                    maturity,
                    evidence_cell,
                )
            )
        lines.append("")
    lines += [
        "Related self-hosted loop artifact:",
        "",
        "- [skill-forge-loop](prompts/skill-forge-driver.md) runs the jar-wide",
        "  forge queue tracked in `agent-state/SKILL_FORGE_TRACKER.md`.",
        "",
        "See [evidence-model.md](evidence-model.md) for metadata semantics.",
        "",
    ]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate or verify skills.json (exit 0/1).")
    parser.add_argument("--check", action="store_true",
                        help="verify skills.json is in sync; write nothing")
    args = parser.parse_args(argv)

    index = build_index()
    expected = render(index)
    expected_core = render_core_doc(index)
    n = len(index["skills"])
    if args.check:
        stale = []
        if not INDEX.exists() or INDEX.read_text(encoding="utf-8") != expected:
            stale.append("skills.json")
        if not CORE_DOC.exists() or CORE_DOC.read_text(encoding="utf-8") != expected_core:
            stale.append("docs/core-skills.md")
        if stale:
            print("FAIL: generated index files are stale -- run scripts/gen-index.py: "
                  + ", ".join(stale))
            return 1
        print("OK: generated index files in sync (%d skills)" % n)
        return 0

    INDEX.write_text(expected, encoding="utf-8")
    CORE_DOC.parent.mkdir(parents=True, exist_ok=True)
    CORE_DOC.write_text(expected_core, encoding="utf-8")
    print("wrote %s and %s (%d skills)" % (INDEX, CORE_DOC, n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
